backend:
  name: github
  branch: master
  repo: Randallonius/gatsby-starter-netlifycms

media_folder: src/images

collections: 
  - name: 'post'
    label: 'Post'
    folder: 'src/posts'
    create: true
    slug: '{{slug}}'
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'author', name: 'author', widget: 'string'}
      - { label: 'featuredImage', name: 'featuredImage', widget: 'image'}
      - { label: 'slug', name: 'slug' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
